config/routes.rb
HiremeApp::Application.routes.draw do
  devise_for :users, path: "/", path_names: { sign_in: 'login', sign_out: 'logout'}
  root "experiences#index"
  get '/home' => "home#index"
  resources :experiences do
    resources :notes
  end

  
  

end

app/models/experience.rb
class Experience < ActiveRecord::Base
	validates :title, presence: true

	has_many :notes
	belongs_to :user
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :experience
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :experiences
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_user!
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: [:show, :edit, :update, :destroy]

  # GET /experiences
  # GET /experiences.json

  def index
    @experiences = current_user.experiences
# raise
  end

  # GET /experiences/1
  # GET /experiences/1.json
  def show
    @note = Note.new
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences
  # POST /experiences.json
  def create
    @experience = Experience.new(experience_params)
    current_user.experiences << @experience
    if @experience.save
      redirect_to @experience, notice: 'Experience was successfully created.' 
    else
      render action: 'new' 
    end
  end

  # PATCH/PUT /experiences/1
  # PATCH/PUT /experiences/1.json
  def update
      if @experience.update(experience_params)
        redirect_to @experience, notice: 'Experience was successfully updated.'
      else
        render action: 'edit'
      end
  end

  # DELETE /experiences/1
  # DELETE /experiences/1.json
  def destroy
    @experience.destroy
    redirect_to experiences_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experience_params
      params.require(:experience).permit(:title, :content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	skip_before_filter :authenticate_user!
	def index
	end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @experience = Experience.find(params[:experience_id])
    @note = @experience.notes.new(note_params)

    respond_to do |format|
      if @experience.save
        format.html { redirect_to @experience, notice: 'Note was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:topic, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def resource_class
  	devise_mapping.to
  end
  
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/experiences/_form.html.erb
<%= form_for(@experience) do |f| %>
  <% if @experience.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h2>

      <ul>
      <% @experience.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/experiences/edit.html.erb
<h1>Editing experience</h1>

<%= render 'form' %>

<%= link_to 'Show', @experience %> |
<%= link_to 'Back', experiences_path %>

app/views/experiences/index.html.erb
<div class="media">
  <a class="pull-left" href="#">
    <img class="media-object" src="assets/me.jpg">
  </a>
  <div class="media-body">
    <b><h1 class="media-heading">ETA</h1>
    <p>Project Manager</p>
    <p>New York, New York  |  Computer Software</p></b>
  </div>
</div>

<h2>Summary</h2>
<p>
• Project Manager, Product Manager, Product Marketing Manager, Product Engineer<br>

<h3 class="list">Experiences</h3>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>

    <table class="table">
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= experience.title %></td>
        <td><%= experience.content %></td>
        <td><%= link_to 'Show', experience_path(experience) %></td>
        <td><%= link_to 'Edit', edit_experience_path(experience) %></td>
        <td><%= link_to 'Destroy', experience, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <tr>
      <td></td>
      <td>
        <ul>
          <% experience.notes.each do |note| %>
          <li><%= link_to note.topic, note.content, target:"_blank" %></li>
          <% end %>
        </ul>
      </td>
    </tr>
    <% end %>
    </table>


  </tbody>
</table>

<%= link_to 'New Experience', new_experience_path %>

<br>
<br>

<p>
<h4><b>Education</b></h4>
<br>
Back-End Web Development (Ruby / Ruby on Rails)<br>
General Assembly, New York, NY<br>
• Learned fundamentals of an object-oriented programming language (Ruby), ability to build functional web application using Rails, and implement web applications using database solutions; Third Party APIs; Ruby Gems; and GitHub.<br>
<br>d
Professional Certification in Project Management<br>
New York University, New York, NY<br>
• Agile Project Management; Project Management for Information Systems; Basic Project Management; Project Communications Management; and Risk and Change Management.<br>
<br>
Professional Certification in Digital Media Marketing<br>
New York University, New York, NY<br>
• Digital Strategy - Creating Synergy in Marketing Program; Strategic Search Engine Marketing (SEM / SEO); Web Analytics - Integrating Website and Email Data for Effective Digital Marketing Programs; Data Analytics, Interpretation, and Reporting; and Interactive Marketing.<br>
<br>
Bachelor of Science in Electrical Engineering<br>
California Polytechnic State University, San Luis Obispo, CA<br>
• Alpha Gamma Sigma Honor Society, Mathematics Engineering Science Achievement
• Society of Women Engineers - Electrical Engineering Major Chair and Student Electrical Engineering Council Representative<br>
</p>

<br>

<p>
<h5><b>Activities</b></h5>
<br>
Kids in the Game (Our Lady Queen of Angels Elementary School, NYC)<br>
• Volunteer teacher in after school sports program<br>
<br>
New York Flyers Running Club<br>
• Treasurer and Executive Board Member & Active Member<br>
• Finance / accounting and system administrator responsibilities utilizing Chase online banking, PayPal, and Quicken.<br>
<br>
Junior Chamber International<br>
• Project Chair & Active Member<br>
• Chaired and organized community service projects creating positive change.<br>
<br>
Technology; Long Distance Running (2013 Boston Marathon Finisher), Traveling, Listening to Music, Reading, Cooking<br>
</p>

<br>
<br>
<br>

app/views/experiences/new.html.erb
<h1>New Experience</h1>

<%= render 'form' %>

<%= link_to 'Back', experiences_path %>

app/views/experiences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @experience.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @experience.content %>
</p>

<%= link_to 'Edit', edit_experience_path(@experience) %> |
<%= link_to 'Back', experiences_path %>

<hr>
<h3> Notes </h3>
<% @experience.notes.each do |note| %>
	<p><%= note.topic %></p> <p><%= note.content %></p>
	<br>
<% end %>

<%= render "notes/form" %>

app/views/home/index.html.erb
<div class="jumbotron box">
	<h1>Welcome to HireMe!</h1>
  	<p>Showcase your professional experience, work samples, and discover opportunities.</p>
  	<p>Get started with your free account.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>


<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div id="navbar-wrapper">
  <div class="container-fluid">
      <a class="navbar-brand" href="http://desolate-anchorage-2481.herokuapp.com/">HireMe</a>
<% if !current_user  %>
   <div class="form-group" id="signin-input-wrapper">
    <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), class:"navbar-form navbar-left", role:"search", id:"signin-navbar") do |f| %>
      
        <div class="signin-input" id="email-input">
          <%= f.email_field :email, :autofocus => true, placeholder:"email", class:"form-control", type:"text"%>
        </div>
        <div class="signin-input" id="">
          <%= f.password_field :password, placeholder:"password", class:"form-control"%>
        </div>
      
      <%= f.submit "Sign in", class:"btn btn-default" , type:"submit"%>
    <% end %>
    </div>
  <% else %>
    <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
    </ul>
  <% end %>
  </div>
</div>
</nav>


<head>
  <title>HiremeApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<body class="bgcolor2">

	<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
	
	<% if user_signed_in? %>
		<p class="user">You are signed in as <%= current_user.email %></p>
    <%= yield %>
	<% else %>
		<%- if controller_name != 'sessions' %>
  			<%= link_to "Sign in", new_session_path(User) %><br />
		<% end -%>
  		<%= link_to "Sign up", new_registration_path(User) %><br />
  	

  		<div class="jumbotron box";>
  		<div class="container";>
		  <center>
		  <h1>Welcome to HireMe!</h1>
  		  <p>Showcase your professional experience, work samples, and discover opportunities. Get started with your free account.</p>
		  </center>
		</div>
    </div>
	<% end -%>
	

</body>

<nav class="navbar navbar-default navbar-fixed-bottom" role="navigation">
  <div class="container">
    <p class="navbar-text pull-left">2014 HireMe, LLC  |  Made in NYC</p>
  </div>
</nav>

</html>

app/views/notes/_form.html.erb
<%= form_for([@experience, @note]) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :topic %><br>
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.topic %></td>
        <td><%= note.content %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<%= link_to 'New Note', new_note_path %>
<%= link_to 'New Note', new_note_path %>
<%= link_to 'New Note', new_note_path %>
<%= link_to 'New Note', new_note_path %>
<%= link_to 'New Note', new_note_path %>
<%= link_to 'New Note', new_note_path %>
<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @note.topic %>
</p>

<p>
  <strong>Content:</strong>
  <%= @note.content %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>